### ISSUE TITLE
[a11y] Tag <h1></h1> não contém texto perceptível por leitores de tela e mecanismos de busca

### ISSUE THREAD

**Issue by fititnt** [talitapagani/gaia#5]
Todas as páginas do site, tem o seguinte código:

``` html
<h1 class="logo"> <a href="/"></a></h1>
```

``` css
@media only screen and (min-width: 37.5rem)
.bar-header .logo a:after {
    content: 'Projeto GAIA';
}
```

Porém isso gera problemas com leitores de tela e mecanismos de busca.

**Sugestão**:

Ou usar texto puro, ou usar uma imagem com alt, que já é o suficiente para resolver esse problema. O exemplo abaixo funciona caso queira usar imagem em vez de texto puro

``` html
<h1 class="brand pull-left">
  <a href="/">
    <img alt="Programador &amp; consultor focado em Web Standards .::. Joomla!, PHP, Javascript, UI/UX" title="Voltar à página inicial" width="150" height="64" src="data:image/png;base64,iVBORw0...">
  </a>
</h1>
```

Ele usará no outline o texto **Programador &amp; consultor focado em Web Standards .::. Joomla!, PHP, Javascript, UI/UX** enquanto ao passar o mouse por cima, ao menos para usuários desktop, irá indicar **Voltar à página inicial**
